### ISSUE TITLE
Path not found for Tokenization.

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-processing/signwriting-transcription#9]
Dear Friend. 
The link for tokenization 
`
https://github.com/sign-language-processing/signbank-plus/blob/main/signbank_plus/signwriting/signwriting_tokenizer.py`

Is not active or accessible.

**Comment by AmitMY** [comment]
Where is this link?
The correct link to the tokenizer is https://github.com/sign-language-processing/signwriting/tree/main/signwriting/tokenizer

**Comment by Tortoise17** [comment]
The home page or main page of this repo, under the heading Tokenization.
